import {
  BatteryCharging,
  Building2,
  ClipboardCheck,
  Droplets,
  Factory,
  FileBadge,
  House,
  Waves,
  Wrench,
} from '@lucide/vue'

export const services = [
  {
    id: 'residential',
    title: 'Residential Solar',
    icon: House,
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=85',
    description: 'Elegant rooftop systems designed around your home, energy use, and long-term goals.',
    benefits: ['Lower monthly bills', 'Greater energy independence', 'Higher property value'],
    overview: 'A complete home energy solution combining site-specific engineering, premium panels, intelligent inverters, and optional battery backup.',
    idealCustomers: 'Homeowners, villas, apartments, and residential communities.',
    features: ['Custom roof layout', 'App-based monitoring', 'Net-metering support', 'Battery-ready architecture'],
    timeline: 'Survey, design, approvals, installation, and activation.',
    installationTime: '1–3 days',
  },
  {
    id: 'commercial',
    title: 'Commercial Solar',
    icon: Building2,
    image: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1200&q=85',
    description: 'Turn underused roof space into predictable savings and measurable sustainability.',
    benefits: ['Reduced operating costs', 'ESG progress', 'Predictable energy'],
    overview: 'High-performance solar engineered for offices, retail, hospitality, institutions, and multi-site organizations.',
    idealCustomers: 'Offices, schools, hospitals, hotels, retail, and warehouses.',
    features: ['Load-profile analysis', 'Scalable capacity', 'Performance reporting', 'Flexible financing'],
    timeline: 'Energy audit, engineering, approvals, phased installation, commissioning.',
    installationTime: '2–6 weeks',
  },
  {
    id: 'industrial',
    title: 'Industrial Solar',
    icon: Factory,
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
    description: 'Robust, high-output systems engineered for demanding operations and complex sites.',
    benefits: ['Major demand savings', 'Peak-load support', 'Long-term cost control'],
    overview: 'Utility-scale thinking applied to factories, plants, and industrial campuses with rigorous engineering and safety controls.',
    idealCustomers: 'Manufacturing plants, processing facilities, logistics hubs, and large campuses.',
    features: ['HT/LT integration', 'Advanced SCADA', 'Structural engineering', 'Phased deployment'],
    timeline: 'Feasibility, detailed engineering, procurement, construction, grid synchronization.',
    installationTime: '6–16 weeks',
  },
  {
    id: 'water-heater',
    title: 'Solar Water Heater',
    icon: Waves,
    image: 'https://images.unsplash.com/photo-1548337138-e87d889cc369?auto=format&fit=crop&w=1200&q=85',
    description: 'Reliable hot water powered by sunlight, with minimal running cost and maintenance.',
    benefits: ['Up to 80% heating savings', 'Low maintenance', 'Year-round comfort'],
    overview: 'Efficient solar thermal systems sized for daily demand and local climate conditions.',
    idealCustomers: 'Homes, hotels, hostels, hospitals, gyms, and kitchens.',
    features: ['Insulated storage', 'Backup heating option', 'Corrosion protection', 'Weather-resistant frame'],
    timeline: 'Demand assessment, placement review, installation, temperature testing.',
    installationTime: '1–2 days',
  },
  {
    id: 'solar-pump',
    title: 'Solar Pump',
    icon: Droplets,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=85',
    description: 'Dependable, off-grid water pumping that reduces fuel use and operating effort.',
    benefits: ['No fuel dependency', 'Reliable irrigation', 'Remote operation'],
    overview: 'Solar pumping systems matched to water depth, flow requirements, and daily agricultural demand.',
    idealCustomers: 'Farms, estates, rural communities, and water-management projects.',
    features: ['AC/DC pump options', 'Dry-run protection', 'Remote monitoring', 'Durable mounting'],
    timeline: 'Water assessment, pump sizing, array installation, flow validation.',
    installationTime: '2–4 days',
  },
  {
    id: 'battery',
    title: 'Battery Storage',
    icon: BatteryCharging,
    image: 'https://images.unsplash.com/photo-1592833159155-c62df1b65634?auto=format&fit=crop&w=1200&q=85',
    description: 'Store surplus solar energy for evenings, outages, and smarter peak-time use.',
    benefits: ['Backup power', 'Higher self-consumption', 'Peak-rate savings'],
    overview: 'Safe, intelligent storage integrated with new or existing solar systems for greater control and resilience.',
    idealCustomers: 'Homes, critical businesses, clinics, offices, and remote properties.',
    features: ['Smart energy controls', 'Expandable capacity', 'Seamless changeover', 'Real-time monitoring'],
    timeline: 'Load review, battery sizing, integration, protection testing.',
    installationTime: '1–3 days',
  },
  {
    id: 'maintenance',
    title: 'Solar Maintenance',
    icon: Wrench,
    image: 'https://images.unsplash.com/photo-1624397640148-949b1732bb0a?auto=format&fit=crop&w=1200&q=85',
    description: 'Preventive care and expert diagnostics that protect output and system life.',
    benefits: ['Higher uptime', 'Early fault detection', 'Protected warranty'],
    overview: 'Professional inspection, cleaning, testing, and corrective service for systems of every size.',
    idealCustomers: 'Any residential, commercial, or industrial solar-system owner.',
    features: ['Thermal inspection', 'Electrical testing', 'Panel cleaning', 'Performance analysis'],
    timeline: 'Inspection, diagnostics, service report, corrective work.',
    installationTime: 'Same-day service',
  },
  {
    id: 'amc',
    title: 'AMC Services',
    icon: ClipboardCheck,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=85',
    description: 'Proactive annual care with scheduled visits, monitoring, and priority support.',
    benefits: ['Predictable maintenance', 'Priority response', 'Detailed reporting'],
    overview: 'A structured annual maintenance program that keeps systems safe, efficient, and fully documented.',
    idealCustomers: 'Businesses, industries, institutions, communities, and portfolio owners.',
    features: ['Scheduled servicing', 'Remote monitoring', 'Priority callouts', 'Annual health report'],
    timeline: 'Baseline audit, service calendar, ongoing monitoring, annual review.',
    installationTime: '12-month coverage',
  },
  {
    id: 'government-subsidy',
    title: 'Government Subsidy',
    icon: FileBadge,
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=85',
    description: 'Clear guidance through PM Surya Ghar and other eligible solar subsidy programs.',
    benefits: ['Eligibility clarity', 'Paperwork support', 'Faster approvals'],
    overview:
      'We help you understand subsidy options, prepare documents, and coordinate with DISCOM processes so you claim what you qualify for without confusion.',
    idealCustomers: 'Residential homeowners and eligible institutions applying under current solar schemes.',
    features: ['Scheme guidance', 'Document checklist', 'Application support', 'Net-metering coordination'],
    timeline: 'Eligibility review, document prep, application filing, follow-up until sanction.',
    installationTime: 'Parallel with project timeline',
  },
]

export function getServiceById(id) {
  return services.find((service) => service.id === id) || null
}

export function servicePath(id) {
  return `/services/${id}`
}
